//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinePlaces.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NinePlaces.Localization.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity:.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach.
        /// </summary>
        public static string Beach {
            get {
                return ResourceManager.GetString("Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach.
        /// </summary>
        public static string BeachHoverText {
            get {
                return ResourceManager.GetString("BeachHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach: {0}.
        /// </summary>
        public static string BeachHoverTextDetails {
            get {
                return ResourceManager.GetString("BeachHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach Name:.
        /// </summary>
        public static string BeachName {
            get {
                return ResourceManager.GetString("BeachName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        public static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        public static string BoatHoverText {
            get {
                return ResourceManager.GetString("BoatHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat to {0}.
        /// </summary>
        public static string BoatHoverTextDetails {
            get {
                return ResourceManager.GetString("BoatHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat to .
        /// </summary>
        public static string BoatTo {
            get {
                return ResourceManager.GetString("BoatTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string BusHoverText {
            get {
                return ResourceManager.GetString("BusHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus to {0}.
        /// </summary>
        public static string BusHoverTextDetails {
            get {
                return ResourceManager.GetString("BusHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping.
        /// </summary>
        public static string Camping {
            get {
                return ResourceManager.GetString("Camping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping.
        /// </summary>
        public static string CampingHoverText {
            get {
                return ResourceManager.GetString("CampingHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping at {0}.
        /// </summary>
        public static string CampingHoverTextDetails {
            get {
                return ResourceManager.GetString("CampingHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road-trip.
        /// </summary>
        public static string CarHoverText {
            get {
                return ResourceManager.GetString("CarHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road-trip to {0}.
        /// </summary>
        public static string CarHoverTextDetails {
            get {
                return ResourceManager.GetString("CarHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Flights!.
        /// </summary>
        public static string CheckForFlights {
            get {
                return ResourceManager.GetString("CheckForFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Activity Details.
        /// </summary>
        public static string EditActivityDetails {
            get {
                return ResourceManager.GetString("EditActivityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Camping Details.
        /// </summary>
        public static string EditCampingDetails {
            get {
                return ResourceManager.GetString("EditCampingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Details.
        /// </summary>
        public static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Event Details.
        /// </summary>
        public static string EditEventDetails {
            get {
                return ResourceManager.GetString("EditEventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Flight Itinerary.
        /// </summary>
        public static string EditFlightItinerary {
            get {
                return ResourceManager.GetString("EditFlightItinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Meet-Up Details.
        /// </summary>
        public static string EditMeetUpDetails {
            get {
                return ResourceManager.GetString("EditMeetUpDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reservation Details.
        /// </summary>
        public static string EditReservation {
            get {
                return ResourceManager.GetString("EditReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Road-trip Details.
        /// </summary>
        public static string EditRoadTrip {
            get {
                return ResourceManager.GetString("EditRoadTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sightseeing Details.
        /// </summary>
        public static string EditSightseeingDetails {
            get {
                return ResourceManager.GetString("EditSightseeingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Stay Details.
        /// </summary>
        public static string EditStayDetails {
            get {
                return ResourceManager.GetString("EditStayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Travel Details.
        /// </summary>
        public static string EditTravelDetails {
            get {
                return ResourceManager.GetString("EditTravelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event:.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Hotel!.
        /// </summary>
        public static string FindHotel {
            get {
                return ResourceManager.GetString("FindHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        public static string Flight {
            get {
                return ResourceManager.GetString("Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        public static string FlightHoverText {
            get {
                return ResourceManager.GetString("FlightHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight to {0}.
        /// </summary>
        public static string FlightHoverTextDetails {
            get {
                return ResourceManager.GetString("FlightHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight to .
        /// </summary>
        public static string FlightTo {
            get {
                return ResourceManager.GetString("FlightTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &amp; Lodging.
        /// </summary>
        public static string FoodLodging {
            get {
                return ResourceManager.GetString("FoodLodging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string GenericActivity {
            get {
                return ResourceManager.GetString("GenericActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string GenericActivityHoverText {
            get {
                return ResourceManager.GetString("GenericActivityHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string GenericActivityHoverTextDetails {
            get {
                return ResourceManager.GetString("GenericActivityHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Tickets!.
        /// </summary>
        public static string GetTickets {
            get {
                return ResourceManager.GetString("GetTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home City.
        /// </summary>
        public static string HomeCity {
            get {
                return ResourceManager.GetString("HomeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel: .
        /// </summary>
        public static string HotelDesc {
            get {
                return ResourceManager.GetString("HotelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string HotelHoverText {
            get {
                return ResourceManager.GetString("HotelHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel: {0}.
        /// </summary>
        public static string HotelHoverTextDetails {
            get {
                return ResourceManager.GetString("HotelHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Name:.
        /// </summary>
        public static string HotelName {
            get {
                return ResourceManager.GetString("HotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Reservation.
        /// </summary>
        public static string HotelReservation {
            get {
                return ResourceManager.GetString("HotelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House:.
        /// </summary>
        public static string HouseEdit {
            get {
                return ResourceManager.GetString("HouseEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string HouseHoverText {
            get {
                return ResourceManager.GetString("HouseHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House: {0}.
        /// </summary>
        public static string HouseHoverTextDetails {
            get {
                return ResourceManager.GetString("HouseHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your timeline contains vacations that were created while signed out.
        ///Would you like these vacations to be imported to your account?.
        /// </summary>
        public static string ImportTimelinePrompt {
            get {
                return ResourceManager.GetString("ImportTimelinePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect EMail/Password Combination.
        /// </summary>
        public static string IncorrectEmailPass {
            get {
                return ResourceManager.GetString("IncorrectEmailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address....
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Home City....
        /// </summary>
        public static string InvalidHomeCity {
            get {
                return ResourceManager.GetString("InvalidHomeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name....
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOADING.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lodging.
        /// </summary>
        public static string Lodging {
            get {
                return ResourceManager.GetString("Lodging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as:.
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Reservation!.
        /// </summary>
        public static string MakeReservation {
            get {
                return ResourceManager.GetString("MakeReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet-Up.
        /// </summary>
        public static string MeetUp {
            get {
                return ResourceManager.GetString("MeetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet-Up.
        /// </summary>
        public static string MeetUpHoverText {
            get {
                return ResourceManager.GetString("MeetUpHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet-Up with {0}.
        /// </summary>
        public static string MeetUpHoverTextDetails {
            get {
                return ResourceManager.GetString("MeetUpHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet-Up with .
        /// </summary>
        public static string MeetUpWith {
            get {
                return ResourceManager.GetString("MeetUpWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memories.
        /// </summary>
        public static string Memories {
            get {
                return ResourceManager.GetString("Memories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Vacations.
        /// </summary>
        public static string MyVacations {
            get {
                return ResourceManager.GetString("MyVacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightlife.
        /// </summary>
        public static string Nightlife {
            get {
                return ResourceManager.GetString("Nightlife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightlife.
        /// </summary>
        public static string NightlifeHoverText {
            get {
                return ResourceManager.GetString("NightlifeHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightlife: {0}.
        /// </summary>
        public static string NightlifeHoverTextDetails {
            get {
                return ResourceManager.GetString("NightlifeHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NotesHoverText {
            get {
                return ResourceManager.GetString("NotesHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: {0}.
        /// </summary>
        public static string NotesHoverTextDetails {
            get {
                return ResourceManager.GetString("NotesHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other....
        /// </summary>
        public static string OtherActivies {
            get {
                return ResourceManager.GetString("OtherActivies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Activity.
        /// </summary>
        public static string Outdoor {
            get {
                return ResourceManager.GetString("Outdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Activity.
        /// </summary>
        public static string OutdoorHoverText {
            get {
                return ResourceManager.GetString("OutdoorHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string OutdoorHoverTextDetails {
            get {
                return ResourceManager.GetString("OutdoorHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords did not match....
        /// </summary>
        public static string PasswordReentryMismatch {
            get {
                return ResourceManager.GetString("PasswordReentryMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too short....
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Password.
        /// </summary>
        public static string PasswordVerify {
            get {
                return ResourceManager.GetString("PasswordVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string PhotosHoverText {
            get {
                return ResourceManager.GetString("PhotosHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos of {0}.
        /// </summary>
        public static string PhotosHoverTextDetails {
            get {
                return ResourceManager.GetString("PhotosHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant: .
        /// </summary>
        public static string RestaurantDesc {
            get {
                return ResourceManager.GetString("RestaurantDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant:.
        /// </summary>
        public static string RestaurantEdit {
            get {
                return ResourceManager.GetString("RestaurantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Reservation.
        /// </summary>
        public static string RestaurantHoverText {
            get {
                return ResourceManager.GetString("RestaurantHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant: {0}.
        /// </summary>
        public static string RestaurantHoverTextDetails {
            get {
                return ResourceManager.GetString("RestaurantHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Reservation.
        /// </summary>
        public static string RestaurantReservation {
            get {
                return ResourceManager.GetString("RestaurantReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road-trip.
        /// </summary>
        public static string RoadTrip {
            get {
                return ResourceManager.GetString("RoadTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road-trip to .
        /// </summary>
        public static string RoadTripTo {
            get {
                return ResourceManager.GetString("RoadTripTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string ShoppingHoverText {
            get {
                return ResourceManager.GetString("ShoppingHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping: {0}.
        /// </summary>
        public static string ShoppingHoverTextDetails {
            get {
                return ResourceManager.GetString("ShoppingHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowHoverText {
            get {
                return ResourceManager.GetString("ShowHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show: {0}.
        /// </summary>
        public static string ShowHoverTextDetails {
            get {
                return ResourceManager.GetString("ShowHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sightseeing.
        /// </summary>
        public static string Sightseeing {
            get {
                return ResourceManager.GetString("Sightseeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sightseeing.
        /// </summary>
        public static string SightseeingHoverText {
            get {
                return ResourceManager.GetString("SightseeingHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sightseeing: {0}.
        /// </summary>
        public static string SightseeingHoverTextDetails {
            get {
                return ResourceManager.GetString("SightseeingHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up!.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporting Event.
        /// </summary>
        public static string SportingEvent {
            get {
                return ResourceManager.GetString("SportingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporting Event.
        /// </summary>
        public static string SportingEventHoverText {
            get {
                return ResourceManager.GetString("SportingEventHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporting Event: {0}.
        /// </summary>
        public static string SportingEventHoverTextDetails {
            get {
                return ResourceManager.GetString("SportingEventHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Suggestion.
        /// </summary>
        public static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string SuggestionsHoverText {
            get {
                return ResourceManager.GetString("SuggestionsHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions {0}.
        /// </summary>
        public static string SuggestionsHoverTextDetails {
            get {
                return ResourceManager.GetString("SuggestionsHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string TrainHoverText {
            get {
                return ResourceManager.GetString("TrainHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train to {0}.
        /// </summary>
        public static string TrainHoverTextDetails {
            get {
                return ResourceManager.GetString("TrainHoverTextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        public static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photos!.
        /// </summary>
        public static string UploadPhotos {
            get {
                return ResourceManager.GetString("UploadPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VACATION: .
        /// </summary>
        public static string VacationTitle {
            get {
                return ResourceManager.GetString("VacationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Route with Google Maps.
        /// </summary>
        public static string ViewRoute {
            get {
                return ResourceManager.GetString("ViewRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where:.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who:.
        /// </summary>
        public static string Who {
            get {
                return ResourceManager.GetString("Who", resourceCulture);
            }
        }
    }
}
